FROM node:lts-alpine AS builder

WORKDIR src/

COPY package.json .
COPY yarn.lock .

RUN yarn

ADD . .

RUN yarn build


# Distributable image
FROM nginx:alpine

COPY --from=build /src/build /usr/share/nginx/html
