name: publish Linode Cloud Manager

on:
  push:
    branches: [ ci/publish-manager, ci/action-demo ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn --frozen-lockfile
    - run: yarn workspace @linode/api-v4 test
    - run: yarn workspace @linode/api-v4 build
    - run: yarn workspace linode-manager test
    - run: yarn workspace linode-manager build
      env:
        REACT_APP_APP_ROOT: https://${{ secrets.AWS_S3_BUCKET }}.website-us-east-1.linodeobjects.com
        REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_ENDPOINT: https://us-east-1.linodeobjects.com
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        SOURCE_DIR: packages/manager/build

  deploy:
    runs-on: ubuntu-latest
    outputs:
      username: ${{ steps.hello.outputs.username }}
    steps:
      - id: hello
        uses: stvnjacobs/github-actions-linode@v1
        with:
          linodeToken: ${{ secrets.LINODE_TOKEN }}
      - run: echo ${{ steps.hello.outputs.username }}

  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.deploy.outputs.username }}
